ALTER TABLE tutors
    ADD COLUMN celular VARCHAR(20),
    ADD COLUMN email VARCHAR(150),

    ADD COLUMN cep VARCHAR(10),
    ADD COLUMN logradouro VARCHAR(150),
    ADD COLUMN numero VARCHAR(20),
    ADD COLUMN complemento VARCHAR(100),
    ADD COLUMN bairro VARCHAR(100),
    ADD COLUMN cidade VARCHAR(100),
    ADD COLUMN uf VARCHAR(2);